# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d531b8184e20df8c34f58cb911208e75718ee8fa40f44d0931c97fff572f8833b01f7490b7a0dfcecd21d4c5af2e9ca6a1a8e230ff04856aecc68c11b438651

test:
  secret_key_base: 0490ee0c155cf21932104cd05fdf0db72ce534e5f5224307c2857cff50ac772719d74e433b94192e33ff03406262817a46ec1511111a42788001d8bca66693a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
